from __future__ import annotations

# ruff: noqa: E501
from estate_assessment.models import Dependency, SourceSystem

SYSTEMS: list[SourceSystem] = [
    SourceSystem(
        system_id="legacy_tms",
        system_name="Legacy Transport Management System",
        engine="SQL Server",
        assumed_version="SQL Server 2016 compatibility profile",
        business_domain="Transport operations",
        workload_type="transactional OLTP; operational reporting; event history",
        database_size_gb=180.0,
        database_size_evidence="synthetic assumption",
        annual_growth_pct=28.0,
        growth_evidence="synthetic assumption",
        transaction_volume_per_day=85_000,
        transaction_volume_evidence="derived evidence",
        peak_workload="weekday depot handover windows and customer-service escalation periods",
        availability_requirement="business critical",
        rto_minutes=60,
        rpo_minutes=15,
        data_sensitivity="confidential operational data with synthetic contact fields",
        dependencies="billing_ops; depot_reference_feed; carrier_updates; operational_events",
        integration_patterns="stored procedures; file export; JSON payloads; event history table",
        authentication_model="legacy SQL/application authentication assumption",
        operational_owner="Transport operations platform team",
        business_criticality="high",
        downtime_tolerance_minutes=45,
        support_constraints="stored procedure coupling and legacy data types require remediation",
        technical_debt_indicators="ntext; money; datetime; JSON in nvarchar(max); reporting on OLTP",
    ),
    SourceSystem(
        system_id="billing_ops",
        system_name="Billing and Service Operations",
        engine="PostgreSQL-like relational source",
        assumed_version="PostgreSQL 13 compatibility profile",
        business_domain="Finance and customer service",
        workload_type="transactional billing; customer-service case management",
        database_size_gb=65.0,
        database_size_evidence="synthetic assumption",
        annual_growth_pct=18.0,
        growth_evidence="synthetic assumption",
        transaction_volume_per_day=22_000,
        transaction_volume_evidence="derived evidence",
        peak_workload="month-end billing and Monday support backlog",
        availability_requirement="important",
        rto_minutes=240,
        rpo_minutes=60,
        data_sensitivity="confidential billing and customer-service notes",
        dependencies="legacy_tms shipment identifiers; customer identifier mapping",
        integration_patterns="relational extracts; case-note exports; customer_ref identifier mismatch",
        authentication_model="database user/service credential assumption",
        operational_owner="Finance systems team",
        business_criticality="medium",
        downtime_tolerance_minutes=180,
        support_constraints="cross-source identifier mismatch must be reconciled",
        technical_debt_indicators="jsonb legacy attributes; inconsistent customer_ref vs customer_id",
    ),
    SourceSystem(
        system_id="depot_partner_feeds",
        system_name="Depot and Carrier File Feeds",
        engine="CSV/JSON file feeds",
        assumed_version="flat-file partner integration",
        business_domain="Depot operations and carrier integration",
        workload_type="batch integration",
        database_size_gb=8.0,
        database_size_evidence="synthetic assumption",
        annual_growth_pct=35.0,
        growth_evidence="synthetic assumption",
        transaction_volume_per_day=12_000,
        transaction_volume_evidence="derived evidence",
        peak_workload="carrier update bursts during morning dispatch",
        availability_requirement="operationally important",
        rto_minutes=480,
        rpo_minutes=240,
        data_sensitivity="internal operational reference and status data",
        dependencies="legacy_tms external_order_ref; depot_code",
        integration_patterns="CSV; JSON; schema_version; schema drift",
        authentication_model="file-share or partner transfer assumption",
        operational_owner="Integration operations team",
        business_criticality="medium",
        downtime_tolerance_minutes=240,
        support_constraints="schema drift and duplicate records require landing-zone validation",
        technical_debt_indicators="nullable required fields; schema variation; duplicate business keys",
    ),
    SourceSystem(
        system_id="shipment_event_stream",
        system_name="Shipment Operational Event Fixtures",
        engine="JSONL event fixture",
        assumed_version="event contract v1 with controlled v2 drift",
        business_domain="Transport operations integration",
        workload_type="event/streaming source",
        database_size_gb=25.0,
        database_size_evidence="synthetic assumption",
        annual_growth_pct=45.0,
        growth_evidence="synthetic assumption",
        transaction_volume_per_day=340_000,
        transaction_volume_evidence="derived evidence",
        peak_workload="status-event bursts from depot scanners",
        availability_requirement="business critical for tracking freshness",
        rto_minutes=120,
        rpo_minutes=15,
        data_sensitivity="internal operational movement events",
        dependencies="legacy_tms shipment identifiers",
        integration_patterns="JSONL; duplicate delivery; out-of-order events; schema_version",
        authentication_model="event producer identity assumption",
        operational_owner="Transport integration team",
        business_criticality="high",
        downtime_tolerance_minutes=60,
        support_constraints="ordering and idempotency must be solved before streaming ingestion",
        technical_debt_indicators="duplicate event delivery; late events; schema drift",
    ),
]


DEPENDENCIES: list[Dependency] = [
    Dependency(
        "DEP-001",
        "Transport web application",
        "legacy_tms",
        "application_database",
        "application_to_database",
        "synthetic assumption",
        "Stored procedures create and update shipments.",
        "Application coupling affects target selection and cutover sequencing.",
    ),
    Dependency(
        "DEP-002",
        "dbo.usp_CreateShipment",
        "dbo.Shipment",
        "stored_procedure_table",
        "procedure_to_table",
        "locally measured",
        "Procedure inserts Shipment rows and derives route/customer identifiers.",
        "Stored procedure compatibility and test coverage required before migration.",
    ),
    Dependency(
        "DEP-003",
        "dbo.usp_UpdateShipmentStatus",
        "dbo.ShipmentEventHistory",
        "stored_procedure_history",
        "procedure_to_table",
        "locally measured",
        "Procedure updates Shipment and appends event history.",
        "CDC/event sourcing behaviour must be preserved.",
    ),
    Dependency(
        "DEP-004",
        "billing_ops.invoice",
        "legacy_tms.Shipment",
        "cross_system_identifier",
        "billing_to_transport",
        "derived evidence",
        "Invoices reference shipment_id and ACCT-style customer_ref.",
        "Identifier mapping must be remediated before integrated analytics.",
    ),
    Dependency(
        "DEP-005",
        "depot_reference_feed.csv",
        "legacy_tms.Depot",
        "file_feed_reference",
        "file_to_database",
        "locally measured",
        "Depot feed uses depot_code and includes nullable capacity defect.",
        "Landing validation required before ingestion.",
    ),
    Dependency(
        "DEP-006",
        "carrier_updates.json",
        "legacy_tms.Shipment",
        "partner_status_feed",
        "file_to_database",
        "locally measured",
        "Carrier updates reference external_order_ref and schema_version.",
        "Schema drift and partner status mapping affect ingestion design.",
    ),
    Dependency(
        "DEP-007",
        "shipment_operational_events.jsonl",
        "legacy_tms.Shipment",
        "event_producer",
        "event_to_database",
        "locally measured",
        "Events reference aggregate_id using shipment identifiers.",
        "Streaming ingestion must implement idempotency and ordering.",
    ),
    Dependency(
        "DEP-008",
        "Operational reporting query",
        "legacy_tms.Shipment",
        "reporting_consumer",
        "consumer_to_database",
        "locally measured",
        "Workload query groups depot, route, status and recent shipment age.",
        "Candidate to move from OLTP to analytical serving.",
    ),
    Dependency(
        "DEP-009",
        "Legacy database users",
        "future Entra identities",
        "identity_transition",
        "security_dependency",
        "requires live estate validation",
        "Current authentication model is an assumption, not measured telemetry.",
        "Identity discovery required before migration execution.",
    ),
    Dependency(
        "DEP-010",
        "Daily carrier import schedule",
        "depot_partner_feeds",
        "operational_schedule",
        "scheduler_to_feed",
        "synthetic assumption",
        "Batch windows are assumed from operating model.",
        "Scheduling and replay windows must be validated with source owners.",
    ),
]
