from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REQUIRED_PATHS = [
    ".editorconfig",
    ".gitignore",
    ".github/workflows/ci.yml",
    ".github/workflows/sql-cd.yml",
    ".github/CODEOWNERS",
    ".pre-commit-config.yaml",
    "Makefile",
    "README.md",
    "databricks.yml",
    "pyproject.toml",
    "infra/main.bicep",
    "infra/parameters/dev.bicepparam",
    "infra/parameters/test.bicepparam",
    "infra/parameters/prod.bicepparam",
    "src/azure_sql/README.md",
    "src/databricks/README.md",
    "src/data_engineering/README.md",
    "src/ai/README.md",
    "src/security_governance/README.md",
    "src/observability/README.md",
    "src/legacy_estate/generator.py",
    "src/legacy_estate/workload.py",
    "src/legacy_estate/contracts.py",
    "src/estate_assessment/cli.py",
    "src/estate_assessment/rules.py",
    "src/estate_assessment/inventory.py",
    "src/estate_assessment/validation.py",
    "src/target_architecture/cli.py",
    "src/target_architecture/catalog.py",
    "src/target_architecture/model.py",
    "src/target_architecture/validation.py",
    "src/migration_factory/cli.py",
    "src/migration_factory/catalog.py",
    "src/migration_factory/execution.py",
    "src/migration_factory/model.py",
    "src/migration_factory/validation.py",
    "src/azure_sql_operations/cli.py",
    "src/azure_sql_operations/catalog.py",
    "src/azure_sql_operations/model.py",
    "src/azure_sql_operations/validation.py",
    "src/sql_performance/cli.py",
    "src/sql_performance/catalog.py",
    "src/sql_performance/model.py",
    "src/sql_performance/validation.py",
    "src/sql_cicd/cli.py",
    "src/sql_cicd/catalog.py",
    "src/sql_cicd/model.py",
    "src/sql_cicd/validation.py",
    "src/sql_ai/cli.py",
    "src/sql_ai/catalog.py",
    "src/sql_ai/chunking.py",
    "src/sql_ai/model.py",
    "src/sql_ai/retrieval.py",
    "src/sql_ai/validation.py",
    "src/application_integration/cli.py",
    "src/application_integration/catalog.py",
    "src/application_integration/model.py",
    "src/application_integration/validation.py",
    "src/fabric_integration/cli.py",
    "src/fabric_integration/catalog.py",
    "src/fabric_integration/model.py",
    "src/fabric_integration/validation.py",
    "src/final_assurance/cli.py",
    "src/final_assurance/catalog.py",
    "src/final_assurance/validation.py",
    "src/databricks_foundation/cli.py",
    "src/databricks_foundation/catalog.py",
    "src/databricks_foundation/model.py",
    "src/databricks_foundation/validation.py",
    "src/databricks_pipelines/cli.py",
    "src/databricks_pipelines/catalog.py",
    "src/databricks_pipelines/model.py",
    "src/databricks_pipelines/transformations.py",
    "src/databricks_pipelines/validation.py",
    "src/databricks_orchestration/cli.py",
    "src/databricks_orchestration/catalog.py",
    "src/databricks_orchestration/model.py",
    "src/databricks_orchestration/quality.py",
    "src/databricks_orchestration/validation.py",
    "src/databricks_operations/cli.py",
    "src/databricks_operations/catalog.py",
    "src/databricks_operations/model.py",
    "src/databricks_operations/validation.py",
    "scripts/validate_sql_cicd.py",
    "scripts/validate_sql_ai.py",
    "scripts/validate_application_integration.py",
    "scripts/validate_fabric_integration.py",
    "scripts/validate_final_assurance.py",
    "scripts/check_no_secrets.py",
    "scripts/check_generated_outputs.py",
    "scripts/build_sql_project.py",
    "scripts/test_sql_project.py",
    "scripts/validate_databricks_foundation.py",
    "scripts/validate_databricks_pipelines.py",
    "scripts/validate_databricks_orchestration.py",
    "scripts/validate_databricks_operations.py",
    "src/azure_sql/database_project/legacy_tms/legacy_tms.sqlproj",
    "src/azure_sql/database_project/legacy_tms/README.md",
    "src/azure_sql/database_project/legacy_tms/Schemas/dbo.sql",
    "src/azure_sql/database_project/legacy_tms/Tables/dbo.CustomerAccount.sql",
    "src/azure_sql/database_project/legacy_tms/Tables/dbo.Shipment.sql",
    "src/azure_sql/database_project/legacy_tms/Tables/dbo.ShipmentEventHistory.sql",
    "src/azure_sql/database_project/legacy_tms/Views/dbo.vw_OpenShipmentsByDepot.sql",
    "src/azure_sql/database_project/legacy_tms/StoredProcedures/dbo.usp_CreateShipment.sql",
    "src/azure_sql/database_project/legacy_tms/StoredProcedures/dbo.usp_UpdateShipmentStatus.sql",
    "src/azure_sql/database_project/legacy_tms/Security/RolesAndPermissions.sql",
    "src/azure_sql/database_project/legacy_tms/Security/DataProtection.sql",
    "src/azure_sql/database_project/legacy_tms/PreDeployment/PreDeployment.sql",
    "src/azure_sql/database_project/legacy_tms/PostDeployment/PostDeployment.sql",
    "src/azure_sql/database_project/legacy_tms/PostDeployment/ReferenceData.sql",
    "src/azure_sql/database_project/legacy_tms/Tests/static_schema_tests.sql",
    "src/azure_sql/database_project/legacy_tms/Schemas/ai.sql",
    "src/azure_sql/database_project/legacy_tms/Tables/ai.Document.sql",
    "src/azure_sql/database_project/legacy_tms/Tables/ai.DocumentChunk.sql",
    "src/azure_sql/database_project/legacy_tms/Tables/ai.EmbeddingMetadata.sql",
    "src/azure_sql/database_project/legacy_tms/Tables/ai.RetrievalAudit.sql",
    "src/azure_sql/database_project/legacy_tms/Tables/ai.GenerationAudit.sql",
    "src/azure_sql/database_project/legacy_tms/StoredProcedures/ai.usp_AssembleRagContext.sql",
    "src/azure_sql/database_project/legacy_tms/Security/AiRolesAndPermissions.sql",
    "src/azure_sql/database_project/legacy_tms/Indexes/ai.Document.IX_ai_Document_ShipmentAccount.sql",
    "src/azure_sql/database_project/legacy_tms/Indexes/ai.DocumentChunk.IX_ai_DocumentChunk_Metadata.sql",
    "src/azure_sql/database_project/legacy_tms/Indexes/ai.EmbeddingMetadata.IX_ai_EmbeddingMetadata_WorkQueue.sql",
    "infra/modules/azure-sql/managed-instance.bicep",
    "infra/modules/application-integration/container-apps.bicep",
    "infra/modules/databricks/foundation.bicep",
    "infra/modules/databricks/README.md",
    "src/databricks/unity_catalog/sql/01_catalogs_schemas.sql",
    "src/databricks/unity_catalog/sql/02_tables_views_volumes.sql",
    "src/databricks/unity_catalog/sql/03_security_governance.sql",
    "src/databricks/unity_catalog/sql/04_audit_lineage_queries.sql",
    "src/databricks/common/paths.py",
    "src/databricks/common/schemas.py",
    "src/databricks/pipelines/batch_ingestion.py",
    "src/databricks/pipelines/autoloader_carrier_updates.py",
    "src/databricks/pipelines/streaming_shipment_events.py",
    "src/databricks/transformations/silver_transformations.py",
    "src/databricks/models/scd_type2_customer.sql",
    "src/databricks/models/gold_products.sql",
    "src/databricks/notebooks/ingestion_entrypoint.py",
    "src/databricks/quality/expectations.py",
    "src/databricks/orchestration/job_entrypoints.py",
    "src/databricks/operations/sql/system_table_monitoring.sql",
    "src/databricks/operations/sql/jobs_failed.sql",
    "src/databricks/operations/sql/jobs_long_running.sql",
    "src/databricks/operations/sql/compute_utilization.sql",
    "src/databricks/operations/sql/sql_warehouse_latency.sql",
    "src/databricks/operations/sql/cost_attribution.sql",
    "src/databricks/operations/sql/audit_activity.sql",
    "src/databricks/operations/sql/quality_gate_failures.sql",
    "src/databricks/operations/sql/streaming_health.sql",
    "src/databricks/operations/policies/cluster_policy_examples.json",
    "src/azure_sql/operations/security/01_roles_and_permissions.sql",
    "src/azure_sql/operations/security/02_data_protection.sql",
    "src/azure_sql/operations/agent_jobs/01_integrity_check_job.sql",
    "src/azure_sql/operations/agent_jobs/02_statistics_maintenance_job.sql",
    "src/azure_sql/operations/kql/sqlmi_resource_health.kql",
    "src/azure_sql/performance/query_store/01_configure_query_store.sql",
    "src/azure_sql/performance/query_store/02_diagnostics.sql",
    "src/azure_sql/performance/dmv/query_performance.sql",
    "src/azure_sql/performance/indexing/01_reporting_index_scenario.sql",
    "src/azure_sql/performance/statistics/02_targeted_update_statistics.sql",
    "src/azure_sql/performance/blocking/blocking_scenarios.sql",
    "src/azure_sql/performance/deadlock/deadlock_xevent.sql",
    "src/azure_sql/performance/parameter_sensitivity/customer_summary_by_tier.sql",
    "src/azure_sql/ai/schema/01_ai_tables.sql",
    "src/azure_sql/ai/chunking/ai_generate_chunks_example.sql",
    "src/azure_sql/ai/embeddings/create_external_model_example.sql",
    "src/azure_sql/ai/embeddings/ai_generate_embeddings_example.sql",
    "src/azure_sql/ai/search/full_text_search.sql",
    "src/azure_sql/ai/search/vector_search.sql",
    "src/azure_sql/ai/search/hybrid_rrf.sql",
    "src/azure_sql/ai/rag/sql_native_rag_sequence.sql",
    "src/azure_sql/ai/security/ai_security.sql",
    "src/azure_sql/ai/audit/audit_queries.sql",
    "src/azure_sql/ai/examples/context_payload.sql",
    "src/azure_sql/ai/examples/environment_placeholders.json",
    "src/azure_sql/api/01_api_views.sql",
    "src/azure_sql/api/02_api_procedures.sql",
    "src/azure_sql/api/security/01_api_roles_permissions.sql",
    "src/api/dab/dab-config.production.json",
    "src/api/contracts/openapi.yaml",
    "src/api/contracts/graphql-examples.graphql",
    "src/api/mcp/tool-catalog.md",
    "src/api/mcp/tool-schemas.json",
    "src/api/container/Dockerfile",
    "src/api/container/.env.example",
    "src/api/kql/application_api_observability.kql",
    "src/azure_sql/legacy_oltp/sqlserver/01_tables.sql",
    "src/azure_sql/legacy_oltp/sqlserver/02_constraints.sql",
    "src/azure_sql/legacy_oltp/sqlserver/03_indexes.sql",
    "src/azure_sql/legacy_oltp/sqlserver/04_views.sql",
    "src/azure_sql/legacy_oltp/sqlserver/05_stored_procedures.sql",
    "src/azure_sql/legacy_oltp/sqlserver/07_workload_queries.sql",
    "src/azure_sql/target_sqlmi/01_tables.sql",
    "src/azure_sql/target_sqlmi/02_constraints_indexes.sql",
    "src/azure_sql/target_sqlmi/03_stored_procedures.sql",
    "src/data_engineering/secondary_sources/postgres_billing/schema.sql",
    "src/data_engineering/secondary_sources/postgres_billing/target_flexible_server_schema.sql",
    "docs/architecture/overview.md",
    "docs/architecture/data-flows.md",
    "docs/architecture/security-governance.md",
    "docs/architecture/environments.md",
    "docs/roadmap.md",
    "docs/synthetic-data-strategy.md",
    "docs/legacy-estate.md",
    "docs/estate-assessment.md",
    "docs/target-state-architecture.md",
    "docs/migration-factory.md",
    "docs/azure-sql-operations.md",
    "docs/sql-performance-engineering.md",
    "docs/sql-database-lifecycle.md",
    "docs/databricks-platform-foundation.md",
    "docs/databricks-ingestion-medallion.md",
    "docs/databricks-data-quality-orchestration.md",
    "docs/databricks-monitoring-optimization.md",
    "docs/sql-ai-rag.md",
    "docs/application-api-integration.md",
    "docs/fabric-integration-boundary.md",
    "docs/portfolio-release.md",
    "docs/runbooks/README.md",
    "docs/runbooks/databricks-governance-access-review.md",
    "docs/runbooks/databricks-audit-investigation.md",
    "docs/runbooks/databricks-failed-ingestion-job.md",
    "docs/runbooks/databricks-quality-gate-failure.md",
    "docs/runbooks/databricks-schema-drift.md",
    "docs/runbooks/databricks-freshness-breach.md",
    "docs/runbooks/databricks-streaming-checkpoint-failure.md",
    "docs/runbooks/databricks-backfill-replay-request.md",
    "docs/runbooks/databricks-repeated-task-failure.md",
    "docs/runbooks/databricks-quarantined-record-remediation.md",
    "docs/runbooks/databricks-slow-job.md",
    "docs/runbooks/databricks-job-failure.md",
    "docs/runbooks/databricks-spark-skew-shuffle.md",
    "docs/runbooks/databricks-memory-spill.md",
    "docs/runbooks/databricks-table-health.md",
    "docs/runbooks/databricks-streaming-lag.md",
    "docs/runbooks/databricks-checkpoint-failure.md",
    "docs/runbooks/databricks-sql-warehouse-latency.md",
    "docs/runbooks/databricks-unexpected-cost.md",
    "docs/runbooks/databricks-failed-optimization.md",
    "docs/runbooks/databricks-stale-gold-product.md",
    "docs/runbooks/sql-database-release-rollback.md",
    "docs/runbooks/schema-drift-remediation.md",
    "docs/runbooks/sql-ai-failed-embedding-generation.md",
    "docs/runbooks/sql-ai-stale-embeddings.md",
    "docs/runbooks/sql-ai-vector-dimension-mismatch.md",
    "docs/runbooks/sql-ai-retrieval-quality-regression.md",
    "docs/runbooks/sql-ai-azure-openai-invocation-failure.md",
    "docs/runbooks/sql-ai-grounding-failure.md",
    "docs/runbooks/sql-ai-data-leakage-security-incident.md",
    "docs/adr/README.md",
    "docs/adr/template.md",
    "docs/adr/0006-azure-sql-vs-postgresql-disposition.md",
    "docs/adr/0007-relational-vs-cosmos-db-disposition.md",
    "docs/adr/0008-retain-vs-migrate-and-migration-ordering.md",
    "docs/adr/0009-adls-delta-medallion-architecture.md",
    "docs/adr/0010-databricks-table-boundaries-and-ingestion-modes.md",
    "docs/adr/0011-private-networking-target-architecture.md",
    "docs/adr/0012-ha-dr-and-environment-isolation.md",
    "docs/adr/0013-databricks-workspace-and-catalog-isolation.md",
    "docs/adr/0014-unity-catalog-managed-vs-external-assets.md",
    "docs/adr/0015-databricks-compute-and-federation-boundaries.md",
    "tests/test_foundation.py",
    "tests/test_legacy_estate.py",
    "tests/test_estate_assessment.py",
    "tests/test_migration_factory.py",
    "tests/test_sql_performance.py",
    "scripts/validate_assessment.py",
    "scripts/validate_architecture.py",
    "scripts/validate_migration.py",
    "scripts/validate_azure_sql_operations.py",
    "scripts/validate_sql_performance.py",
    "data/README.md",
    "data/schemas/README.md",
    "data/contracts/shipment_operational_event.schema.json",
    "data/contracts/depot_reference_feed.schema.json",
    "data/contracts/carrier_update.schema.json",
    "data/contracts/databricks/bronze_legacy_tms_changes.schema.json",
    "data/contracts/databricks/bronze_billing_ops_invoices.schema.json",
    "data/contracts/databricks/bronze_depot_reference_feed.schema.json",
    "data/contracts/databricks/bronze_carrier_updates.schema.json",
    "data/contracts/databricks/bronze_customer_service_export.schema.json",
    "data/contracts/databricks/bronze_shipment_operational_events.schema.json",
    "data/contracts/databricks/silver_shipments.schema.json",
    "data/contracts/databricks/gold_delivery_delay_metrics.schema.json",
    "data/samples/legacy_estate/tiny/manifest.json",
    "data/samples/legacy_estate/tiny/workload.jsonl",
    "outputs/database_estate_inventory.csv",
    "outputs/estate_dependencies.csv",
    "outputs/compatibility_assessment.csv",
    "outputs/workload_classification.csv",
    "outputs/target_service_decisions.csv",
    "outputs/migration_complexity.csv",
    "outputs/migration_wave_plan.csv",
    "outputs/modernisation_risk_register.csv",
    "reports/estate_assessment_report.md",
    "outputs/architecture/workload_target_matrix.csv",
    "outputs/architecture/security_control_matrix.csv",
    "outputs/architecture/recovery_strategy_matrix.csv",
    "outputs/architecture/architecture_traceability.csv",
    "outputs/architecture/environment_matrix.csv",
    "outputs/architecture/assumption_register.csv",
    "outputs/architecture/target_component_catalog.csv",
    "reports/target_architecture_report.md",
    "outputs/migration/migration_manifest.csv",
    "outputs/migration/compatibility_remediation.csv",
    "outputs/migration/schema_conversion_report.csv",
    "outputs/migration/data_reconciliation.csv",
    "outputs/migration/validation_gates.csv",
    "outputs/migration/migration_wave_execution.csv",
    "outputs/migration/cutover_readiness.csv",
    "outputs/migration/rollback_readiness.csv",
    "outputs/migration/tool_integration_points.csv",
    "outputs/migration/failure_scenarios.csv",
    "reports/migration_factory_report.md",
    "outputs/azure_sql_operations/configuration_baseline.csv",
    "outputs/azure_sql_operations/security_role_matrix.csv",
    "outputs/azure_sql_operations/sensitive_data_controls.csv",
    "outputs/azure_sql_operations/monitoring_catalog.csv",
    "outputs/azure_sql_operations/alert_catalog.csv",
    "outputs/azure_sql_operations/automation_catalog.csv",
    "outputs/azure_sql_operations/backup_restore_readiness.csv",
    "outputs/azure_sql_operations/ha_dr_readiness.csv",
    "outputs/azure_sql_operations/operational_readiness.csv",
    "reports/azure_sql_operations_report.md",
    "outputs/sql_performance/workload_catalog.csv",
    "outputs/sql_performance/performance_baseline.csv",
    "outputs/sql_performance/query_analysis.csv",
    "outputs/sql_performance/index_recommendations.csv",
    "outputs/sql_performance/statistics_strategy.csv",
    "outputs/sql_performance/blocking_scenarios.csv",
    "outputs/sql_performance/deadlock_readiness.csv",
    "outputs/sql_performance/parameter_sensitivity.csv",
    "outputs/sql_performance/performance_regression_controls.csv",
    "outputs/sql_performance/performance_assurance.csv",
    "reports/sql_performance_report.md",
    "outputs/sql_cicd/sql_project_inventory.csv",
    "outputs/sql_cicd/database_object_traceability.csv",
    "outputs/sql_cicd/reference_data_manifest.csv",
    "outputs/sql_cicd/deployment_safety_rules.csv",
    "outputs/sql_cicd/schema_drift_scenarios.csv",
    "outputs/sql_cicd/environment_promotion_matrix.csv",
    "outputs/sql_cicd/database_test_catalog.csv",
    "outputs/sql_cicd/performance_regression_gate.csv",
    "outputs/sql_cicd/security_regression_gate.csv",
    "outputs/sql_cicd/release_readiness.csv",
    "outputs/sql_cicd/release_manifest.json",
    "reports/sql_cicd_report.md",
    "outputs/sql_ai/ai_use_case_catalog.csv",
    "outputs/sql_ai/ai_schema_catalog.csv",
    "outputs/sql_ai/document_source_matrix.csv",
    "outputs/sql_ai/chunking_strategy.csv",
    "outputs/sql_ai/embedding_configuration.csv",
    "outputs/sql_ai/embedding_lifecycle.csv",
    "outputs/sql_ai/change_detection_strategy.csv",
    "outputs/sql_ai/lexical_search_catalog.csv",
    "outputs/sql_ai/vector_search_catalog.csv",
    "outputs/sql_ai/hybrid_retrieval_strategy.csv",
    "outputs/sql_ai/retrieval_evaluation_dataset.csv",
    "outputs/sql_ai/retrieval_evaluation_results.csv",
    "outputs/sql_ai/rag_context_contract.csv",
    "outputs/sql_ai/rag_execution_steps.csv",
    "outputs/sql_ai/ai_security_matrix.csv",
    "outputs/sql_ai/ai_data_exposure_matrix.csv",
    "outputs/sql_ai/ai_audit_catalog.csv",
    "outputs/sql_ai/ai_failure_handling.csv",
    "outputs/sql_ai/ai_cost_controls.csv",
    "outputs/sql_ai/sql_ai_readiness.csv",
    "reports/sql_ai_report.md",
    "outputs/application_integration/api_catalog.csv",
    "outputs/application_integration/dab_entity_catalog.csv",
    "outputs/application_integration/api_authorization_matrix.csv",
    "outputs/application_integration/sensitive_field_exposure.csv",
    "outputs/application_integration/ai_endpoint_contract.csv",
    "outputs/application_integration/mcp_tool_catalog.csv",
    "outputs/application_integration/mcp_security_matrix.csv",
    "outputs/application_integration/hosting_decision.csv",
    "outputs/application_integration/resilience_policy.csv",
    "outputs/application_integration/error_catalog.csv",
    "outputs/application_integration/rate_limit_policy.csv",
    "outputs/application_integration/observability_catalog.csv",
    "outputs/application_integration/audit_traceability.csv",
    "outputs/application_integration/security_test_scenarios.csv",
    "outputs/application_integration/integration_readiness.csv",
    "reports/application_integration_report.md",
    "outputs/fabric_integration/fabric_boundary_matrix.csv",
    "outputs/fabric_integration/fabric_data_product_catalog.csv",
    "outputs/fabric_integration/integration_pattern_decisions.csv",
    "outputs/fabric_integration/fabric_data_contracts.csv",
    "outputs/fabric_integration/schema_compatibility_policy.csv",
    "outputs/fabric_integration/publication_gate.csv",
    "outputs/fabric_integration/freshness_handoff_matrix.csv",
    "outputs/fabric_integration/identity_access_matrix.csv",
    "outputs/fabric_integration/sensitivity_handoff.csv",
    "outputs/fabric_integration/lineage_handoff.csv",
    "outputs/fabric_integration/quality_handoff_manifest.csv",
    "outputs/fabric_integration/failure_responsibility_matrix.csv",
    "outputs/fabric_integration/cost_duplication_controls.csv",
    "outputs/fabric_integration/versioning_policy.csv",
    "outputs/fabric_integration/fabric_integration_readiness.csv",
    "reports/fabric_integration_report.md",
    "outputs/final_assurance/capability_inventory.csv",
    "outputs/final_assurance/architecture_traceability.csv",
    "outputs/final_assurance/platform_ownership_matrix.csv",
    "outputs/final_assurance/security_assurance_matrix.csv",
    "outputs/final_assurance/identity_assurance.csv",
    "outputs/final_assurance/data_product_assurance.csv",
    "outputs/final_assurance/governance_traceability.csv",
    "outputs/final_assurance/resilience_assurance.csv",
    "outputs/final_assurance/failure_mode_matrix.csv",
    "outputs/final_assurance/observability_assurance.csv",
    "outputs/final_assurance/finops_assurance.csv",
    "outputs/final_assurance/ai_assurance.csv",
    "outputs/final_assurance/api_assurance.csv",
    "outputs/final_assurance/cicd_assurance.csv",
    "outputs/final_assurance/implementation_truth_matrix.csv",
    "outputs/final_assurance/production_gap_register.csv",
    "outputs/final_assurance/final_risk_register.csv",
    "outputs/final_assurance/runbook_catalog.csv",
    "outputs/final_assurance/release_readiness.csv",
    "outputs/final_assurance/release_manifest.json",
    "reports/final_assurance_report.md",
    "outputs/databricks_foundation/workspace_strategy.csv",
    "outputs/databricks_foundation/compute_strategy.csv",
    "outputs/databricks_foundation/unity_catalog_namespace.csv",
    "outputs/databricks_foundation/storage_boundary.csv",
    "outputs/databricks_foundation/access_control_matrix.csv",
    "outputs/databricks_foundation/fine_grained_security.csv",
    "outputs/databricks_foundation/governed_tag_catalog.csv",
    "outputs/databricks_foundation/retention_policy.csv",
    "outputs/databricks_foundation/lineage_readiness.csv",
    "outputs/databricks_foundation/audit_catalog.csv",
    "outputs/databricks_foundation/delta_sharing_matrix.csv",
    "outputs/databricks_foundation/federation_decisions.csv",
    "outputs/databricks_foundation/bundle_target_matrix.csv",
    "outputs/databricks_foundation/platform_readiness.csv",
    "reports/databricks_foundation_report.md",
    "outputs/databricks_pipelines/source_ingestion_matrix.csv",
    "outputs/databricks_pipelines/bronze_table_catalog.csv",
    "outputs/databricks_pipelines/silver_transformation_catalog.csv",
    "outputs/databricks_pipelines/gold_product_catalog.csv",
    "outputs/databricks_pipelines/data_model_catalog.csv",
    "outputs/databricks_pipelines/scd_strategy.csv",
    "outputs/databricks_pipelines/schema_drift_matrix.csv",
    "outputs/databricks_pipelines/checkpoint_strategy.csv",
    "outputs/databricks_pipelines/quarantine_rules.csv",
    "outputs/databricks_pipelines/replay_idempotency_matrix.csv",
    "outputs/databricks_pipelines/physical_layout_strategy.csv",
    "outputs/databricks_pipelines/pipeline_traceability.csv",
    "outputs/databricks_pipelines/pipeline_readiness.csv",
    "reports/databricks_pipelines_report.md",
    "outputs/databricks_orchestration/data_quality_rules.csv",
    "outputs/databricks_orchestration/quality_severity_matrix.csv",
    "outputs/databricks_orchestration/quality_results.csv",
    "outputs/databricks_orchestration/quarantine_catalog.csv",
    "outputs/databricks_orchestration/job_catalog.csv",
    "outputs/databricks_orchestration/task_dependency_matrix.csv",
    "outputs/databricks_orchestration/schedule_matrix.csv",
    "outputs/databricks_orchestration/retry_timeout_policy.csv",
    "outputs/databricks_orchestration/failure_handling_matrix.csv",
    "outputs/databricks_orchestration/backfill_strategy.csv",
    "outputs/databricks_orchestration/job_permission_matrix.csv",
    "outputs/databricks_orchestration/orchestration_traceability.csv",
    "outputs/databricks_orchestration/orchestration_readiness.csv",
    "reports/databricks_orchestration_report.md",
    "outputs/databricks_operations/monitoring_catalog.csv",
    "outputs/databricks_operations/job_health_rules.csv",
    "outputs/databricks_operations/pipeline_observability.csv",
    "outputs/databricks_operations/spark_troubleshooting_matrix.csv",
    "outputs/databricks_operations/join_optimization_matrix.csv",
    "outputs/databricks_operations/delta_table_health.csv",
    "outputs/databricks_operations/streaming_health_rules.csv",
    "outputs/databricks_operations/compute_optimization_matrix.csv",
    "outputs/databricks_operations/cluster_policy_catalog.csv",
    "outputs/databricks_operations/sql_warehouse_operations.csv",
    "outputs/databricks_operations/cost_allocation_model.csv",
    "outputs/databricks_operations/cost_optimization_controls.csv",
    "outputs/databricks_operations/alert_catalog.csv",
    "outputs/databricks_operations/operational_slo_matrix.csv",
    "outputs/databricks_operations/operations_readiness.csv",
    "reports/databricks_operations_report.md",
]

REQUIRED_DIRECTORIES = [
    "infra/modules",
    "infra/scripts",
    "src/azure_sql",
    "src/databricks",
    "src/data_engineering",
    "src/ai",
    "src/security_governance",
    "src/observability",
    "src/legacy_estate",
    "src/estate_assessment",
    "src/target_architecture",
    "src/migration_factory",
    "src/azure_sql_operations",
    "src/sql_performance",
    "src/sql_cicd",
    "src/sql_ai",
    "src/application_integration",
    "src/fabric_integration",
    "src/final_assurance",
    "src/databricks_foundation",
    "src/databricks_pipelines",
    "src/databricks_orchestration",
    "src/databricks_operations",
    "src/azure_sql/operations/security",
    "src/azure_sql/operations/agent_jobs",
    "src/azure_sql/operations/kql",
    "src/azure_sql/performance",
    "src/azure_sql/performance/query_store",
    "src/azure_sql/performance/dmv",
    "src/azure_sql/ai",
    "src/azure_sql/ai/schema",
    "src/azure_sql/ai/chunking",
    "src/azure_sql/ai/embeddings",
    "src/azure_sql/ai/search",
    "src/azure_sql/ai/rag",
    "src/azure_sql/ai/security",
    "src/azure_sql/ai/audit",
    "src/azure_sql/ai/examples",
    "src/azure_sql/api",
    "src/azure_sql/api/security",
    "src/api",
    "src/api/dab",
    "src/api/contracts",
    "src/api/mcp",
    "src/api/container",
    "src/api/kql",
    "src/azure_sql/database_project",
    "src/azure_sql/database_project/legacy_tms",
    "src/azure_sql/database_project/legacy_tms/Tables",
    "src/azure_sql/database_project/legacy_tms/Indexes",
    "src/azure_sql/database_project/legacy_tms/PostDeployment",
    "src/databricks/unity_catalog",
    "src/databricks/unity_catalog/sql",
    "src/databricks/bundles",
    "src/databricks/common",
    "src/databricks/pipelines",
    "src/databricks/transformations",
    "src/databricks/models",
    "src/databricks/quality",
    "src/databricks/notebooks",
    "src/databricks/orchestration",
    "src/databricks/operations",
    "src/databricks/operations/sql",
    "src/databricks/operations/policies",
    "infra/modules/databricks",
    "src/azure_sql/legacy_oltp/sqlserver",
    "src/azure_sql/target_sqlmi",
    "src/data_engineering/secondary_sources/postgres_billing",
    "docs/architecture",
    "docs/adr",
    "docs/runbooks",
    "data/raw",
    "data/interim",
    "data/processed",
    "data/schemas",
    "data/contracts",
    "data/contracts/databricks",
    "data/samples/legacy_estate/tiny",
    "outputs",
    "outputs/architecture",
    "outputs/migration",
    "outputs/azure_sql_operations",
    "outputs/sql_performance",
    "outputs/sql_cicd",
    "outputs/sql_ai",
    "outputs/application_integration",
    "outputs/fabric_integration",
    "outputs/final_assurance",
    "outputs/databricks_foundation",
    "outputs/databricks_pipelines",
    "outputs/databricks_orchestration",
    "outputs/databricks_operations",
    "reports",
    "tests",
]

REQUIRED_README_TERMS = [
    "enterprise Azure Data and AI modernisation",
    "Milestone 1",
    "Milestone 2",
    "Milestone 3",
    "Milestone 4",
    "Milestone 5",
    "Milestone 6",
    "Milestone 7",
    "Milestone 8",
    "Milestone 9",
    "Milestone 10",
    "Milestone 11",
    "Milestone 12",
    "Milestone 13",
    "Milestone 14",
    "Milestone 15",
    "Milestone 16",
    "does not deploy Azure resources",
    "synthetic legacy source estate",
    "estate assessment and modernisation decisioning",
    "target-state architecture and platform decisions",
    "migration factory",
    "Azure SQL operational administration model",
    "SQL performance engineering",
    "SQL database development lifecycle",
    "database-as-code",
    "Databricks platform",
    "Unity Catalog foundation",
    "Databricks ingestion",
    "medallion processing",
    "Databricks data quality",
    "Lakeflow Jobs",
    "Databricks monitoring",
    "cost optimization",
    "AI-enabled SQL",
    "vector search",
    "database-native RAG",
    "secure application/API integration",
    "Fabric downstream integration boundary",
    "final cross-platform assurance",
    "Azure SQL",
    "Azure Databricks",
    "managed identity",
    "Bicep",
]


def validate_required_paths() -> list[str]:
    failures: list[str] = []
    for relative_path in REQUIRED_PATHS:
        if not (ROOT / relative_path).is_file():
            failures.append(f"Missing required file: {relative_path}")
    for relative_path in REQUIRED_DIRECTORIES:
        if not (ROOT / relative_path).is_dir():
            failures.append(f"Missing required directory: {relative_path}")
    return failures


def validate_readme_terms() -> list[str]:
    readme = (ROOT / "README.md").read_text(encoding="utf-8").lower()
    return [
        f"README.md missing required term: {term}"
        for term in REQUIRED_README_TERMS
        if term.lower() not in readme
    ]


def validate_adr_metadata() -> list[str]:
    failures: list[str] = []
    adr_files = sorted((ROOT / "docs/adr").glob("[0-9][0-9][0-9][0-9]-*.md"))
    if len(adr_files) < 5:
        failures.append("Expected at least five initial ADRs")
    for adr_file in adr_files:
        text = adr_file.read_text(encoding="utf-8")
        for required in ("- Status:", "- Date:", "## Context", "## Decision", "## Consequences"):
            if required not in text:
                failures.append(f"{adr_file.relative_to(ROOT)} missing {required}")
    return failures


def validate_roadmap_scope() -> list[str]:
    roadmap = (ROOT / "docs/roadmap.md").read_text(encoding="utf-8").lower()
    required_topics = [
        "azure sql modernisation",
        "sql ci/cd",
        "databricks",
        "ingestion",
        "medallion",
        "data quality",
        "operational analytics",
        "vector",
        "hybrid search",
        "rag",
        "monitoring",
        "finops",
        "production assurance",
    ]
    return [
        f"docs/roadmap.md missing topic: {topic}"
        for topic in required_topics
        if topic not in roadmap
    ]


def main() -> int:
    failures = (
        validate_required_paths()
        + validate_readme_terms()
        + validate_adr_metadata()
        + validate_roadmap_scope()
    )
    if failures:
        print("Repository structure validation failed:")
        for failure in failures:
            print(f"- {failure}")
        return 1
    print("Repository structure validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
