ALTER DATABASE [legacy_tms]
SET QUERY_STORE = ON;

ALTER DATABASE [legacy_tms]
SET QUERY_STORE (
    OPERATION_MODE = READ_WRITE,
    QUERY_CAPTURE_MODE = AUTO,
    MAX_STORAGE_SIZE_MB = 1024,
    CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30),
    DATA_FLUSH_INTERVAL_SECONDS = 900,
    INTERVAL_LENGTH_MINUTES = 15,
    WAIT_STATS_CAPTURE_MODE = ON
);

